name = "txipe/ticket-vending-machine"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'txipe/ticket-vending-machine'"

[repository]
user = "txipe"
project = "ticket-vending-machine"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"
