[rpc]
listen_address = "0.0.0.0:3000"

[logging]
max_level = "debug"
include_tokio = true

[ledger]
endpoint_url = "https://mainnet.utxorpc-v0.demeter.run"
api_key = "dmtr_utxorpc1wgnnj0qcfj32zxsz2uc8d4g7uclm2s2w"

[[workers]]
name = "faucet"
module = "faucet.wasm"
config = "faucet.json"
