[rpc]
listen_address = "0.0.0.0:3000"

[logging]
max_level = "debug"
include_tokio = true

[ledger]
endpoint_url = "https://mainnet.utxorpc-v0.demeter.run"
api_key = "dmtr_utxorpc1wgnnj0qcfj32zxsz2uc8d4g7uclm2s2w"

[chainsync]
endpoint_url = "https://mainnet.utxorpc-v0.demeter.run"
api_key = "dmtr_utxorpc1wgnnj0qcfj32zxsz2uc8d4g7uclm2s2w"

[[workers]]
name = "faucet"
module = "../bin/faucet.wasm"
config = "faucet.json"

[[workers]]
name = "wallet"
module = "../bin/wallet.wasm"
config = "wallet.json"


[[workers]]
name = "asteria"
module = "../bin/asteria.wasm"
config = "asteria.json"
