name = "txpipe/minter"
version = "0.0.0"
compiler = "v1.1.3"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'txpipe/minter'"

[repository]
user = "txpipe"
project = "minter"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
